# -*- coding: utf-8 -*-
"""cleanedData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOk1EEIQLCvzlyUSP0zZyN_gTHNpcEup
"""

import numpy as np
import pandas as pd

df = pd.read_csv('LongDataset.csv')

df.columns

df.info()

df.isnull().sum()

df.shape

# Drop rows where 'value' is NaN
df1 = df.dropna(subset=['value']).copy()

print(df1.isnull().sum(),'\n Shape:', df1.shape)

# Build country-to-region mapping from non-null values
region_map = df.dropna(subset=['region']).drop_duplicates(subset='country')[['country', 'region']]
region_dict = dict(zip(region_map['country'], region_map['region']))

# Fill missing regions safely using .loc
df1.loc[:, 'region'] = df1['country'].map(region_dict)

df1.isnull().sum()

df1.drop(columns=['region'], inplace=True)

df1.reset_index(drop=True, inplace=True)

df1.to_csv("cleaned_dataset.csv", index=False)